export default function Head() {
  return (
    <>
      <link
        rel="preload"
        href="/fonts/Timeburner.ttf"
        as="font"
        type="font/ttf"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        href="/fonts/Ballega.otf"
        as="font"
        type="font/otf"
        crossOrigin="anonymous"
      />
      <link
        rel="preload"
        as="image"
        href="/images/NeuroLens.webp"
        type="image/webp"
      />
      <link
        rel="preload"
        as="image"
        href="/images/EchoSkin.webp"
        type="image/webp"
      />
      <link
        rel="preload"
        as="image"
        href="/images/CoreDrive.webp"
        type="image/webp"
      />
    </>
  );
}